name = "Hello-World-2345"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "Hello-World-2345_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "Hello-World-2345.wasm"
command = "npm run build:release"
